from datetime import timedelta
from decimal import Decimal
from random import Random

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError
from django.db import IntegrityError, transaction
from django.utils import timezone
from faker import Faker

from configrations.models import Configuration, ContactUs
from product.models import Category, Client_review, Offer, Product


SEED_PREFIX = "seed_data"
ADMIN_USERNAME = "admin"
ADMIN_EMAIL = "admin@example.com"
ADMIN_PASSWORD = "Admin@12345"


class Command(BaseCommand):
    help = "Seed safe, idempotent development data for project models."

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Delete only records previously generated by this command before seeding.",
        )
        parser.add_argument(
            "--count",
            type=int,
            default=10,
            help="Number of records to create or update for each normal model.",
        )
        parser.add_argument(
            "--seed",
            type=int,
            default=None,
            help="Seed value for reproducible generated data.",
        )

    def handle(self, *args, **options):
        count = options["count"]
        if count < 1:
            raise CommandError("--count must be greater than 0.")

        self.fake = Faker(["en_US", "ar_EG"])
        if options["seed"] is not None:
            Faker.seed(options["seed"])
        self.random = Random(options["seed"])
        self.created_counts = {}
        self.updated_counts = {}

        try:
            with transaction.atomic():
                if options["clear"]:
                    self._clear_seeded_data()

                self.seed_admin_user()
                seed_users = self.seed_review_users(count)
                categories = self.seed_categories(count)
                self.seed_configuration()
                self.seed_contact_messages(count)
                self.seed_products(count, categories)
                self.seed_offers(count)
                self.seed_client_reviews(count, seed_users)
        except (IntegrityError, ValueError) as exc:
            raise CommandError(
                f"Failed while seeding data. Check model constraints and field values. Error: {exc}"
            ) from exc

        self.stdout.write(self.style.SUCCESS("Seed data completed."))
        labels = sorted(set(self.created_counts) | set(self.updated_counts))
        for label in labels:
            created = self.created_counts.get(label, 0)
            updated = self.updated_counts.get(label, 0)
            self.stdout.write(f"{label}: created {created}, updated {updated}")

    def _clear_seeded_data(self):
        deleted = {}
        deleted["Client_review"] = Client_review.objects.filter(review__startswith=SEED_PREFIX).delete()[0]
        deleted["Product"] = Product.objects.filter(name__startswith=SEED_PREFIX).delete()[0]
        deleted["Offer"] = Offer.objects.filter(title__startswith=SEED_PREFIX).delete()[0]
        deleted["ContactUs"] = ContactUs.objects.filter(name__startswith=SEED_PREFIX).delete()[0]
        deleted["Configuration"] = Configuration.objects.filter(email__startswith=f"{SEED_PREFIX}.").delete()[0]
        deleted["Category"] = Category.objects.filter(name__startswith=SEED_PREFIX).delete()[0]

        User = get_user_model()
        deleted["User"] = User.objects.filter(username__startswith=f"{SEED_PREFIX}_user_").delete()[0]

        for label, count in deleted.items():
            self.stdout.write(f"Cleared {count} seeded {label} record(s).")

    def _track(self, label, created):
        bucket = self.created_counts if created else self.updated_counts
        bucket[label] = bucket.get(label, 0) + 1

    def _update_or_create(self, model, lookup, defaults, label):
        try:
            obj, created = model.objects.update_or_create(**lookup, defaults=defaults)
        except Exception as exc:
            fields = ", ".join([*lookup.keys(), *defaults.keys()])
            raise ValueError(f"{model.__name__} failed for fields [{fields}]: {exc}") from exc
        self._track(label, created)
        return obj

    def _sentence(self):
        return self.fake.sentence(nb_words=self.random.randint(8, 14))

    def _paragraph(self):
        return self.fake.paragraph(nb_sentences=self.random.randint(3, 5))

    def seed_admin_user(self):
        User = get_user_model()
        admin, created = User.objects.update_or_create(
            username=ADMIN_USERNAME,
            defaults={
                "email": ADMIN_EMAIL,
                "is_staff": True,
                "is_superuser": True,
                "is_active": True,
            },
        )
        admin.set_password(ADMIN_PASSWORD)
        admin.save(update_fields=["password", "email", "is_staff", "is_superuser", "is_active"])
        self._track("User(admin)", created)

    def seed_review_users(self, count):
        User = get_user_model()
        users = []
        for index in range(count):
            username = f"{SEED_PREFIX}_user_{index + 1:03d}"
            first_name = self.fake.first_name()
            last_name = self.fake.last_name()
            user = self._update_or_create(
                User,
                {"username": username},
                {
                    "email": f"{username}@example.com",
                    "first_name": first_name,
                    "last_name": last_name,
                    "is_staff": False,
                    "is_superuser": False,
                    "is_active": True,
                },
                "User(review)",
            )
            user.set_password("User@12345")
            user.save(update_fields=["password"])
            users.append(user)
        return users

    def seed_categories(self, count):
        categories = []
        category_names = [
            "Fresh Dairy",
            "Cream Desserts",
            "Pastries",
            "Bakery",
            "Family Packs",
            "Seasonal Boxes",
            "Cold Drinks",
            "Sweet Trays",
            "Gift Sets",
            "Breakfast",
        ]
        arabic_names = ["ألبان", "حلويات قشطة", "مخبوزات", "مخبز", "عبوات عائلية", "موسمي", "مشروبات", "صواني", "هدايا", "إفطار"]
        for index in range(count):
            base_name = category_names[index % len(category_names)]
            category = self._update_or_create(
                Category,
                {"name": f"{SEED_PREFIX} {base_name} {index + 1}"},
                {
                    "name_ar": f"{arabic_names[index % len(arabic_names)]} {index + 1}",
                    "display_order": index,
                },
                "Category",
            )
            categories.append(category)
        return categories

    def seed_configuration(self):
        self._update_or_create(
            Configuration,
            {"email": f"{SEED_PREFIX}.contact@example.com"},
            {
                "certificate_description": self._paragraph(),
                "certificate_description_ar": "شهادة جودة للمنتجات الطازجة.",
                "Our_message": self._paragraph(),
                "Our_message_ar": "رسالتنا تقديم منتجات طازجة بخدمة موثوقة.",
                "Our_vision": self._paragraph(),
                "Our_vision_ar": "رؤيتنا أن نكون الاختيار الأول للحلويات الطازجة.",
                "phone_number": self.fake.phone_number()[:20],
                "address": self.fake.address().replace("\n", ", ")[:255],
                "address_ar": "القاهرة، مصر",
                "Technical_innovation": self._paragraph(),
                "Technical_innovation_ar": "نستخدم أدوات حديثة لتحسين جودة الخدمة.",
                "Social_responsibility": self._paragraph(),
                "Social_responsibility_ar": "ندعم المجتمع بمنتجات آمنة ومسؤولة.",
                "Customer_experience": self._paragraph(),
                "Customer_experience_ar": "نركز على تجربة سهلة ومرضية للعميل.",
                "About_the_Center": self._paragraph(),
                "About_the_Center_ar": "السيد قشطة يقدم منتجات طازجة يوميا.",
                "Future_vision": self._paragraph(),
                "Future_vision_ar": "نسعى للتوسع مع الحفاظ على الجودة.",
            },
            "Configuration",
        )

    def seed_contact_messages(self, count):
        for index in range(count):
            self._update_or_create(
                ContactUs,
                {"name": f"{SEED_PREFIX} Contact {index + 1:03d}"},
                {
                    "name_ar": f"عميل تجريبي {index + 1}",
                    "phone_number": self.fake.phone_number()[:30].strip() or "+201000000000",
                    "message": self._paragraph(),
                    "message_ar": "أرغب في معرفة المزيد عن المنتجات والأسعار.",
                },
                "ContactUs",
            )

    def seed_products(self, count, categories):
        product_names = [
            "Fresh Eshta Cup",
            "Cream Kunafa",
            "Honey Feteer",
            "Mini Dessert Box",
            "Family Cream Tray",
            "Date Pastry",
            "Milk Pudding",
            "Seasonal Sweet Jar",
            "Breakfast Cream Pack",
            "Celebration Tray",
        ]
        arabic_names = ["كوب قشطة", "كنافة بالقشطة", "فطير بالعسل", "علبة ميني", "صينية عائلية", "فطيرة تمر", "مهلبية", "برطمان موسمي", "باك إفطار", "صينية احتفال"]
        for index in range(count):
            quantity = self.random.randint(0, 35)
            self._update_or_create(
                Product,
                {"name": f"{SEED_PREFIX} {product_names[index % len(product_names)]} {index + 1}"},
                {
                    "name_ar": f"{arabic_names[index % len(arabic_names)]} {index + 1}",
                    "description": self._paragraph(),
                    "description_ar": "منتج طازج مناسب للطلبات اليومية والمناسبات.",
                    "price": Decimal(self.random.randrange(2500, 25000)) / Decimal("100"),
                    "category": categories[index % len(categories)],
                    "quantity": quantity,
                    "is_visible": index % 5 != 0,
                    "is_available": quantity > 0 and index % 4 != 0,
                    "display_order": index,
                },
                "Product",
            )

    def seed_offers(self, count):
        today = timezone.localdate()
        for index in range(count):
            starts_in = self.random.randint(-10, 10)
            duration = self.random.randint(5, 25)
            start_date = today + timedelta(days=starts_in)
            end_date = start_date + timedelta(days=duration)
            self._update_or_create(
                Offer,
                {"title": f"{SEED_PREFIX} Offer {index + 1:03d}"},
                {
                    "title_ar": f"عرض تجريبي {index + 1}",
                    "description": self._sentence(),
                    "description_ar": "عرض محدود على منتجات مختارة.",
                    "is_active": index % 4 != 0,
                    "start_date": start_date,
                    "end_date": end_date,
                },
                "Offer",
            )

    def seed_client_reviews(self, count, users):
        for index in range(count):
            self._update_or_create(
                Client_review,
                {"user": users[index % len(users)]},
                {
                    "review": f"{SEED_PREFIX} review {index + 1:03d}: {self._sentence()}",
                    "review_ar": f"تجربة ممتازة وجودة المنتجات رائعة رقم {index + 1}.",
                    "rating": self.random.randint(3, 5),
                },
                "Client_review",
            )
