# Generated by Django 5.2.15 on 2026-06-28 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_placeholder_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    if not User.objects.filter(username='legacy_client').exists():
        User.objects.create_user(username='legacy_client', email='legacy@example.com', password='LegacyClient123!')


def migrate_existing_reviews_to_user(apps, schema_editor):
    ClientReview = apps.get_model('product', 'Client_review')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    placeholder_user = User.objects.filter(username='legacy_client').first()
    if placeholder_user is None:
        placeholder_user = User.objects.create_user(username='legacy_client', email='legacy@example.com', password='LegacyClient123!')

    for review in ClientReview.objects.filter(user__isnull=True):
        review.user = placeholder_user
        review.save(update_fields=['user'])


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_placeholder_user, migrations.RunPython.noop),
        migrations.AddField(
            model_name='client_review',
            name='user',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='client_reviews',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(migrate_existing_reviews_to_user, migrations.RunPython.noop),
        migrations.RemoveField(model_name='client_review', name='name'),
        migrations.RemoveField(model_name='client_review', name='name_ar'),
        migrations.AlterField(
            model_name='client_review',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='client_reviews',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
