# Generated by Django 5.2.10 on 2026-06-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='configurations/', verbose_name='certificate_image')),
                ('certificate_description', models.TextField(blank=True, verbose_name='certificate_description')),
                ('certificate_description_ar', models.TextField(blank=True, null=True, verbose_name='certificate_description_ar')),
                ('Our_message', models.TextField(blank=True, verbose_name='Our_message')),
                ('Our_message_ar', models.TextField(blank=True, null=True, verbose_name='Our_message_ar')),
                ('Our_vision', models.TextField(blank=True, verbose_name='Our_vision')),
                ('Our_vision_ar', models.TextField(blank=True, null=True, verbose_name='Our_vision_ar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone_number')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('address_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='address_ar')),
                ('Technical_innovation', models.TextField(blank=True, verbose_name='Technical_innovation')),
                ('Technical_innovation_ar', models.TextField(blank=True, null=True, verbose_name='Technical_innovation_ar')),
                ('Social_responsibility', models.TextField(blank=True, verbose_name='Social responsibility')),
                ('Social_responsibility_ar', models.TextField(blank=True, null=True, verbose_name='Social responsibility_ar')),
                ('Customer_experience', models.TextField(blank=True, verbose_name='Customer experience')),
                ('Customer_experience_ar', models.TextField(blank=True, null=True, verbose_name='Customer experience_ar')),
                ('About_the_Center', models.TextField(blank=True, verbose_name='About_the_Center')),
                ('About_the_Center_ar', models.TextField(blank=True, null=True, verbose_name='About_the_Center_ar')),
                ('Future_vision', models.TextField(blank=True, verbose_name='Future vision')),
                ('Future_vision_ar', models.TextField(blank=True, null=True, verbose_name='Future vision_ar')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
