# Generated by Django 5.2.10 on 2026-06-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='name_ar')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('message', models.TextField(verbose_name='message')),
                ('message_ar', models.TextField(blank=True, null=True, verbose_name='message_ar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
