# Generated by Django 5.2.15 on 2026-08-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0004_alter_configuration_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created_at'),
        ),
    ]
